# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
