# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(default='')),
                ('caption', models.TextField(default='', null=True)),
                ('provider', models.CharField(default='', max_length=200, null=True)),
                ('producer', models.CharField(default='', max_length=200, null=True)),
                ('copyright', models.CharField(default='', max_length=200, null=True)),
                ('crop_standard_src', models.URLField(default='', null=True)),
                ('crop_square_src', models.URLField(default='', null=True)),
                ('crop_wide_src', models.URLField(default='', null=True)),
                ('crop_enlargement_src', models.URLField(default='', null=True)),
                ('crop_custom_src', models.URLField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PullQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('person', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('teaser', models.TextField(default='')),
                ('story_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date published')),
                ('byline', models.TextField(default='', null=True)),
                ('text', models.TextField(default='')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime downloaded')),
                ('outlet', models.CharField(default='', max_length=200)),
                ('images', models.TextField(default='')),
                ('pull_quotes', models.ManyToManyField(to='dataviz.PullQuote')),
            ],
        ),
    ]
