# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
