# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_story_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
