# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('teaser', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('rank', models.IntegerField(null=True)),
            ],
        ),
    ]
